title: Containerization & DevOps
description: "Lab experiments and theory notes for Containerization & DevOps specialization."
author: Sarthak Kamboj
email: kambojsarthak767@gmail.com # Optional: Add your email if you want

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
plugins:

  - jekyll-seo-tag

# URL Settings (Important for GitHub Pages)
url: "https://khattitoffe.github.io/" 
baseurl: "/Containerization_Devops_Lab" 

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - scripts/
  - LICENSE
  
# Optional: Sidebar settings (if supported by theme)
show_downloads: true
google_analytics: 
